#!/usr/bin/env python3

import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screen_name")
        
    tweets = get_user_timeline(sys.argv[1], 50)
        
    # instantiate analyzer
    analyzer = Analyzer()

    
    for i in tweets:
        score = analyzer.analyze(i)
        if score > 0.0:
            print(colored("{} {}".format(score, i), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, i), "red"))
        else:
            print(colored("{} {}".format(score, i), "yellow"))

if __name__ == "__main__":
    main()
